apiVersion: v1
kind: Pod
metadata:
  name: label-pod
  labels:
    env: dev
    project: roboshop
  namespace: roboshop

spec:
  containers:
  - name: label
    image: nginx
    ports:
    - containerPort: 80