apiVersion: v1
kind: Pod
metadata:
  name: resources
  namespace: roboshop
  labels:
    env: dev
    project: roboshop

spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:   #minimum 
        memory: "64Mi"
        cpu: "250m"
      limits:     # maximum
        memory: "128Mi"
        cpu: 500m"
