apiVersion: v1
kind: Pod
metadata:
  name: imagepull
  labels:
    env: dev
    project: roboshop
  namespace: roboshop

spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
    resources:
      requests:
        memory: "100Mi"
        cpu: "250m"
      limits:
        memory: "250Mi"
        cpu: "500m"
    ports:
    - containerPort: 80

