apiVersion: v1
kind: Pod
metadata:
  name: nginx-sample
  lebels:
    env: dev
    project: roboshop

spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    env: dev
    project: roboshop
  ports:
  - name: http
    protocol: Tcp
    port: 80
    targetport: 8080